### ISSUE TITLE
Improve fuzzy search

### ISSUE THREAD

**Issue by baffioso** [SDFIdk/gsearch#178] opened 2023-02-23 22:50 UTC
Searching for hold-an vej in Ballerup with lower case, but getting these results.  
![image](https://user-images.githubusercontent.com/7534153/221048087-9481aca5-3e5e-45ba-8ec5-ee2bf162a022.png)

I need to start typing ballerup in order to get useful result.
![image](https://user-images.githubusercontent.com/7534153/221048472-b25aaa57-1a0c-49e3-9449-d5992daf2824.png)

This might be an issue in https://github.com/SDFIdk/gsearch

**Comment by JesperKock** [comment] 2023-02-24 10:27
Gsearch has phonetic search, ignores symbols and is case-insensitive.

So you will get the same result with `Hol An Vej` as your search query. This is why you see `HOLstebro` results with `an` and `vej` in the names. Because the results in endpoint `husnummer` is sorted by `husnummertekst` as the first criteria then you are seeing the number 1s roadnames as the first results.

Closed because it is a duplicate of https://github.com/SDFIdk/gsearch/issues/28

**Closed by JesperKock** 2023-02-24 10:27 UTC
