### ISSUE TITLE
Service fails with filter parameter in REST call

### ISSUE THREAD

**Issue by sweco-dkgemr** [SDFIdk/gsearch#202] opened 2023-05-24 14:46 UTC
When using the filter parameter in the REST calls to the API it very often fails with a '**BAD_REQUEST**' error and status code 400 giving the message ’**Input invalid**’. This results in a very limited result list, where sometimes addresses, cadastres or the like is left out, which we consider a critical problem/blocker using the new version of the API.
It was not a problem in the previous version where filter was only available as a parameter in some of the ressources.
![Error_screen_1](https://github.com/SDFIdk/gsearch-ui/assets/62336024/8c6bd7a3-8ce5-477c-a08c-edf0d566d212)
![Error_screen_2](https://github.com/SDFIdk/gsearch-ui/assets/62336024/edb1a9e5-3829-4797-a4e8-1a2538949f0a)
![Error_screen_3](https://github.com/SDFIdk/gsearch-ui/assets/62336024/65b1a47d-05a6-4b99-94a4-c9e797e0fa3b)

**Comment by JesperKock** [comment] 2023-05-25 08:28
We are having trouble replicating the issue.
Could you provide more information?

How often do you experience the errors?
Can you provide timestamps?

**Comment by sweco-dkgemr** [comment] 2023-05-25 09:04
I tried to reproduce the error by using this call several times, but could not reproduce the erorr.
https://api.dataforsyningen.dk/rest/gsearch/v1.0/husnummer?token=fd44f26ab5701c01ca9f570e507fe9ab&q=r&limit=10&filter=kommunekode=%270153%27

I suspect the error only occurs when calling several services at the same time.
I reproduced the error again on our own test site and this is the timestamp for the error;

![timestamp](https://github.com/SDFIdk/gsearch/assets/62336024/25d29586-4bb0-4271-9f90-5ba0d28291a7)

We experience the error for approximately 1/4 of the calls

**Comment by sweco-dkgemr** [comment] 2023-05-25 10:12
org.postgresql.util.PSQLException: ERROR: syntax error at or near \"kommunekode\"\n  Where: PL/pgSQL function api.husnummer(text,text,integer,integer) line 137 at RETURN QUERY [statement:\"select (api.husnummer(:q, :where, 1, :limit)).*\", arguments:{positional:{}, named:{q:7,limit:15,where:kommunekode = '0153'kommunekode = '0153'}, finder:[]}]

**Comment by sweco-dkgemr** [comment] 2023-05-25 10:16
Called:

https://api.dataforsyningen.dk/rest/gsearch/v1.0/navngivenvej?q=7&limit=15&token=7030997b12f9e91e9da29f0c6e24a845&filter=kommunekode=%270153%27

Timestamp:

Thu, 25 May 2023 10:10:51 GMT

Error message:

org.postgresql.util.PSQLException: ERROR: syntax error at or near \"ORDER\"\n  Where: PL/pgSQL function api.navngivenvej(text,text,integer,integer) line 113 at RETURN QUERY [statement:\"select (api.navngivenvej(:q, :where, 1, :limit)).*\", arguments:{positional:{}, named:{q:7,limit:15,where:}, finder:[]}]

**Comment by sweco-dkgemr** [comment] 2023-05-25 10:18
Called:

https://api.dataforsyningen.dk/rest/gsearch/v1.0/matrikel?q=7&limit=15&token=7030997b12f9e91e9da29f0c6e24a845&filter=kommunekode=%270153%27

Timestamp:

Thu, 25 May 2023 10:17:10 GMT

Error Message:

org.postgresql.util.PSQLException: ERROR: syntax error at or near \"ORDER\"\n  Where: PL/pgSQL function api.matrikel(text,text,integer,integer) line 121 at RETURN QUERY [statement:\"select (api.matrikel(:q, :where, 1, :limit)).*\", arguments:{positional:{}, named:{q:7,limit:15,where:}, finder:[]}]

**Comment by sweco-dkgemr** [comment] 2023-05-25 10:20
Called:

https://api.dataforsyningen.dk/rest/gsearch/v1.0/postnummer?q=7&limit=15&token=7030997b12f9e91e9da29f0c6e24a845&filter=kommunekode=%270153%27

Timestamp:

Thu, 25 May 2023 10:17:10 GMT

Error message:

org.postgresql.util.PSQLException: ERROR: syntax error at or near "kommunekode"
  Where: PL/pgSQL function api.postnummer(text,text,integer,integer) line 101 at RETURN QUERY [statement:"select (api.postnummer(:q, :where, 1, :limit)).*", arguments:{positional:{}, named:{q:7,limit:15,where:kommunekode = '0153'kommunekode = '0153'}, finder:[]}]

**Comment by Nobralyra** [comment] 2023-05-25 11:14
We have pushed an update.

Can you please test again and provide feedback if it has worked or not?

**Comment by Nobralyra** [comment] 2023-05-25 12:01
For you information we are trying to find a way to replicate the unintentional behavior, so we don't need to ask you every time to check if the problem is fixed. And hopefully faster can find what is causing the behavior.

**Comment by sweco-dkgemr** [comment] 2023-05-25 12:04
It is really no problem.

**Comment by sweco-dkgemr** [comment] 2023-05-25 12:17
I just tried to reduce it to only calling the matrikel resource and i can make several request in a row without causing any errors.
Adding husnummer so that I request results for both matrikel and husnummer at the same time makes it fail in some instances

**Comment by JesperKock** [comment] 2023-05-25 12:50
Could I get you to test again?
We tried increasing the resources available for Gsearch.

**Comment by JesperKock** [comment] 2023-05-26 11:19
We managed to replicate the error and identified where the issue is.
Hopefully we'll have a fix very soon.

**Comment by sweco-dkgemr** [comment] 2023-05-26 11:48
I'm looking forward to that.

**Comment by Nobralyra** [comment] 2023-05-26 13:06
It should be fixed now. It was an issue with ogr.geotools encodeToString that shares memory between the different threads.
https://github.com/SDFIdk/gsearch/commit/2eb754c94b25646e377eaae65f9783a107ee0b74

**Closed by Nobralyra** 2023-05-26 13:06 UTC

**Comment by sweco-dkgemr** [comment] 2023-05-26 13:13
It is working in our end now also. Thanks for quick response and fix.
